- hosts: all
  vars:
    version: "v0.9.1"
    nvim_min_version: "v0.9"
    nvim_urls:
      Darwin: https://github.com/neovim/neovim/releases/download/{{version}}/nvim-macos.tar.gz
      Linux: https://github.com/neovim/neovim/releases/download/{{version}}/nvim-linux64.tar.gz
  roles:
    - nvim/install
  tags:
    - install

- hosts: all

  roles:
    - nvim/deploy
  tags:
    - deploy
