- name: Get checksum
  uri:
    url: "{{ download_file_checksum_url }}"
    return_content: yes
  register: checksum_result

- debug: var=checksum_result

- name: set cs
  set_fact:
    cs: "{{checksum_result.content.split(' ')[0] }}" 

- debug: var=cs

- name: Set checksum method
  set_fact:
    checksum_method: "{{ download_file_checksum_method if download_file_checksum_method is defined else download_file_checksum_url | splitext | last }}"

- debug: var=checksum_method

- name: Set checksum
  set_fact:
    checksum: "{{ cs }}"

- name: Set destination file
  set_fact:
    dest_file: "{{ dest_dir }}/{{ checksum }}-{{ download_file_url | basename }}"

- name: Download file
  get_url:
    url: "{{ download_file_url }}"
    dest: "{{ dest_file }}"
    checksum: "sha256:{{ checksum }}"
  register: download_result
  until: download_result is succeeded
  retries: "{{ download_retries }}"
  delay: "{{ download_delay }}"
  
- name: Assert checksum
  assert:
    that:
     - download_result is succeeded
    msg: "Downloaded file checksum does not match"
